### ISSUE TITLE
GAME - Play live Pong

### ISSUE THREAD

**Issue by aheister70** [Liryvian/ft_transcendence#24]
Users should be able to play a live Pong game versus another player directly on the website. It can be a canvas game, or it can be a game rendered in 3D, it can also be ugly, but in any case, it must be faithful to the original Pong (1972).

TODO: Determine what will be the rules of the game, and if they are exactly the same as in the original Pong game.

**Rules original game:**
Pong is one of the first computer games that ever created. This simple "tennis like" game features two paddles and a ball. The player controls an in-game paddle by moving it vertically across the left or right side of the screen. The goal is to defeat your opponent by being the first one to gain 10 point. A player gets a point once the opponent misses a ball. The game can be played with two human players, or one player against a computer controlled paddle. 

_First refinement result:_

- [x] #38
- [x] #40
- [x] #41
- [x] #42
- [x] #70 
- [x] #69 
- [x] #68 
- [x] #71 
- [ ] #72 
- [x] #150

**Comment by Ryno95** [comment]
- [ ] Create Game invite table and basic endpoints (Instantiate with abstract CRUD endpoints)
